// Code generated by MockGen. DO NOT EDIT.
// Source: ../../repositories/sessions/session_repository.go

// Package mock_model is a generated GoMock package.
package mock_model

import (
	reflect "reflect"

	sessions "github.com/go-park-mail-ru/2023_2_Chaihona_No.1/internal/repositories/sessions"
	gomock "github.com/golang/mock/gomock"
)

// MockSessionRepository is a mock of SessionRepository interface.
type MockSessionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSessionRepositoryMockRecorder
}

// MockSessionRepositoryMockRecorder is the mock recorder for MockSessionRepository.
type MockSessionRepositoryMockRecorder struct {
	mock *MockSessionRepository
}

// NewMockSessionRepository creates a new mock instance.
func NewMockSessionRepository(ctrl *gomock.Controller) *MockSessionRepository {
	mock := &MockSessionRepository{ctrl: ctrl}
	mock.recorder = &MockSessionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionRepository) EXPECT() *MockSessionRepositoryMockRecorder {
	return m.recorder
}

// CheckSession mocks base method.
func (m *MockSessionRepository) CheckSession(sessionID string) (*sessions.Session, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckSession", sessionID)
	ret0, _ := ret[0].(*sessions.Session)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// CheckSession indicates an expected call of CheckSession.
func (mr *MockSessionRepositoryMockRecorder) CheckSession(sessionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckSession", reflect.TypeOf((*MockSessionRepository)(nil).CheckSession), sessionID)
}

// DeleteSession mocks base method.
func (m *MockSessionRepository) DeleteSession(sessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSession", sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSession indicates an expected call of DeleteSession.
func (mr *MockSessionRepositoryMockRecorder) DeleteSession(sessionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSession", reflect.TypeOf((*MockSessionRepository)(nil).DeleteSession), sessionID)
}

// RegisterNewSession mocks base method.
func (m *MockSessionRepository) RegisterNewSession(session sessions.Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterNewSession", session)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterNewSession indicates an expected call of RegisterNewSession.
func (mr *MockSessionRepositoryMockRecorder) RegisterNewSession(session interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterNewSession", reflect.TypeOf((*MockSessionRepository)(nil).RegisterNewSession), session)
}
