// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: comments.proto

package comments

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CommentServiceClient is the client API for CommentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CommentServiceClient interface {
	CreateCommentCtx(ctx context.Context, in *CommentGRPC, opts ...grpc.CallOption) (*Int, error)
	DeleteCommentCtx(ctx context.Context, in *UInt, opts ...grpc.CallOption) (*Nothing, error)
	ChangeCommentCtx(ctx context.Context, in *CommentGRPC, opts ...grpc.CallOption) (*Nothing, error)
}

type commentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCommentServiceClient(cc grpc.ClientConnInterface) CommentServiceClient {
	return &commentServiceClient{cc}
}

func (c *commentServiceClient) CreateCommentCtx(ctx context.Context, in *CommentGRPC, opts ...grpc.CallOption) (*Int, error) {
	out := new(Int)
	err := c.cc.Invoke(ctx, "/comments.CommentService/CreateCommentCtx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentServiceClient) DeleteCommentCtx(ctx context.Context, in *UInt, opts ...grpc.CallOption) (*Nothing, error) {
	out := new(Nothing)
	err := c.cc.Invoke(ctx, "/comments.CommentService/DeleteCommentCtx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentServiceClient) ChangeCommentCtx(ctx context.Context, in *CommentGRPC, opts ...grpc.CallOption) (*Nothing, error) {
	out := new(Nothing)
	err := c.cc.Invoke(ctx, "/comments.CommentService/ChangeCommentCtx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommentServiceServer is the server API for CommentService service.
// All implementations must embed UnimplementedCommentServiceServer
// for forward compatibility
type CommentServiceServer interface {
	CreateCommentCtx(context.Context, *CommentGRPC) (*Int, error)
	DeleteCommentCtx(context.Context, *UInt) (*Nothing, error)
	ChangeCommentCtx(context.Context, *CommentGRPC) (*Nothing, error)
	mustEmbedUnimplementedCommentServiceServer()
}

// UnimplementedCommentServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCommentServiceServer struct {
}

func (UnimplementedCommentServiceServer) CreateCommentCtx(context.Context, *CommentGRPC) (*Int, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCommentCtx not implemented")
}
func (UnimplementedCommentServiceServer) DeleteCommentCtx(context.Context, *UInt) (*Nothing, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCommentCtx not implemented")
}
func (UnimplementedCommentServiceServer) ChangeCommentCtx(context.Context, *CommentGRPC) (*Nothing, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeCommentCtx not implemented")
}
func (UnimplementedCommentServiceServer) mustEmbedUnimplementedCommentServiceServer() {}

// UnsafeCommentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommentServiceServer will
// result in compilation errors.
type UnsafeCommentServiceServer interface {
	mustEmbedUnimplementedCommentServiceServer()
}

func RegisterCommentServiceServer(s grpc.ServiceRegistrar, srv CommentServiceServer) {
	s.RegisterService(&CommentService_ServiceDesc, srv)
}

func _CommentService_CreateCommentCtx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommentGRPC)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentServiceServer).CreateCommentCtx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/comments.CommentService/CreateCommentCtx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentServiceServer).CreateCommentCtx(ctx, req.(*CommentGRPC))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommentService_DeleteCommentCtx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UInt)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentServiceServer).DeleteCommentCtx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/comments.CommentService/DeleteCommentCtx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentServiceServer).DeleteCommentCtx(ctx, req.(*UInt))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommentService_ChangeCommentCtx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommentGRPC)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentServiceServer).ChangeCommentCtx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/comments.CommentService/ChangeCommentCtx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentServiceServer).ChangeCommentCtx(ctx, req.(*CommentGRPC))
	}
	return interceptor(ctx, in, info, handler)
}

// CommentService_ServiceDesc is the grpc.ServiceDesc for CommentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CommentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "comments.CommentService",
	HandlerType: (*CommentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCommentCtx",
			Handler:    _CommentService_CreateCommentCtx_Handler,
		},
		{
			MethodName: "DeleteCommentCtx",
			Handler:    _CommentService_DeleteCommentCtx_Handler,
		},
		{
			MethodName: "ChangeCommentCtx",
			Handler:    _CommentService_ChangeCommentCtx_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "comments.proto",
}
