// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package handlers

import (
	json "encoding/json"
	model "github.com/go-park-mail-ru/2023_2_Chaihona_No.1/internal/model"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6b59ef4cDecodeGithubComGoParkMailRu20232ChaihonaNo1InternalHandlers(in *jlexer.Lexer, out *BodyQuestions) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "questions":
			if in.IsNull() {
				in.Skip()
				out.Questions = nil
			} else {
				in.Delim('[')
				if out.Questions == nil {
					if !in.IsDelim(']') {
						out.Questions = make([]model.Question, 0, 1)
					} else {
						out.Questions = []model.Question{}
					}
				} else {
					out.Questions = (out.Questions)[:0]
				}
				for !in.IsDelim(']') {
					var v1 model.Question
					(v1).UnmarshalEasyJSON(in)
					out.Questions = append(out.Questions, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6b59ef4cEncodeGithubComGoParkMailRu20232ChaihonaNo1InternalHandlers(out *jwriter.Writer, in BodyQuestions) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"questions\":"
		out.RawString(prefix[1:])
		if in.Questions == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Questions {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v BodyQuestions) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6b59ef4cEncodeGithubComGoParkMailRu20232ChaihonaNo1InternalHandlers(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v BodyQuestions) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6b59ef4cEncodeGithubComGoParkMailRu20232ChaihonaNo1InternalHandlers(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *BodyQuestions) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6b59ef4cDecodeGithubComGoParkMailRu20232ChaihonaNo1InternalHandlers(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *BodyQuestions) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6b59ef4cDecodeGithubComGoParkMailRu20232ChaihonaNo1InternalHandlers(l, v)
}
