// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package handlers

import (
	json "encoding/json"
	model "github.com/go-park-mail-ru/2023_2_Chaihona_No.1/internal/model"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonAe7b7331DecodeGithubComGoParkMailRu20232ChaihonaNo1InternalHandlers(in *jlexer.Lexer, out *BodyPayments) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "payments":
			if in.IsNull() {
				in.Skip()
				out.Payments = nil
			} else {
				in.Delim('[')
				if out.Payments == nil {
					if !in.IsDelim(']') {
						out.Payments = make([]model.Payment, 0, 0)
					} else {
						out.Payments = []model.Payment{}
					}
				} else {
					out.Payments = (out.Payments)[:0]
				}
				for !in.IsDelim(']') {
					var v1 model.Payment
					(v1).UnmarshalEasyJSON(in)
					out.Payments = append(out.Payments, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "redirect_url":
			out.RedirectURL = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonAe7b7331EncodeGithubComGoParkMailRu20232ChaihonaNo1InternalHandlers(out *jwriter.Writer, in BodyPayments) {
	out.RawByte('{')
	first := true
	_ = first
	if len(in.Payments) != 0 {
		const prefix string = ",\"payments\":"
		first = false
		out.RawString(prefix[1:])
		{
			out.RawByte('[')
			for v2, v3 := range in.Payments {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	if in.RedirectURL != "" {
		const prefix string = ",\"redirect_url\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.RedirectURL))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v BodyPayments) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonAe7b7331EncodeGithubComGoParkMailRu20232ChaihonaNo1InternalHandlers(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v BodyPayments) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonAe7b7331EncodeGithubComGoParkMailRu20232ChaihonaNo1InternalHandlers(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *BodyPayments) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonAe7b7331DecodeGithubComGoParkMailRu20232ChaihonaNo1InternalHandlers(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *BodyPayments) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonAe7b7331DecodeGithubComGoParkMailRu20232ChaihonaNo1InternalHandlers(l, v)
}
