mockgen: 
	mockgen -source=../../repositories/sessions/session_repository.go -destination=mock_model/mock_session_storage.go -package=mock_model
	mockgen -source=../../repositories/posts/post_repository.go -destination=mock_model/mock_post_storage.go -package=mock_model
	mockgen -source=../../repositories/subscribe_levels/subscribe_level_repository.go -destination=mock_model/mock_subscribe_level_storage.go -package=mock_model
	mockgen -source=../../repositories/subscriptions/subscription_repository.go -destination=mock_model/mock_subscription_storage.go -package=mock_model
	mockgen -source=../../repositories/users/user_repository.go -destination=mock_model/mock_user_storage.go -package=mock_model
